name: Secret String Detection

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch the full history to ensure the main branch is available

    - name: Fetch main branch
      run: git fetch origin main:main # Fetch the main branch specifically

    - name: Scan PR for Sensitive Patterns
      run: |
        # Define regex patterns to identify improper use of keywords
        patterns=(
          "token=[^*]+"      # Detect 'token=' followed by any character other than '*'
          "password=[^*]+"   # Detect 'password=' followed by any character other than '*'
          "apikey=[^*]+"     # Detect 'apikey=' followed by any character other than '*'
          "secret=[^*]+"     # Detect 'secret=' followed by any character other than '*'
          "PRIVATE_KEY=[^*]+" # Detect 'PRIVATE_KEY=' followed by any character other than '*'
          "SECRET_KEY=[^*]+"  # Detect 'SECRET_KEY=' followed by any character other than '*'
        )

        # Fetch the changes introduced in the PR
        git diff main...HEAD > changes.txt

        # Check each pattern in the changes
        for pattern in "${patterns[@]}"; do
          if grep -E "$pattern" changes.txt; then
            echo "Error: Detected sensitive string in the format: $pattern"
            exit 1
          fi
        done

        echo "No sensitive strings detected with improper formats."
