name: Snyk Secret Scan

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop, feature/*]

jobs:
  snyk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: 380c3ffe-5b9e-4d27-80a0-c72029dcf41e
      run: snyk auth $SNYK_TOKEN

    - name: Run Snyk Secrets Scan
      run: snyk code test --severity-threshold=high

